#ifndef GSNIMAGETOOLBOX_GLOBAL_H
#define GSNIMAGETOOLBOX_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GSNIMAGETOOLBOX_LIBRARY)
#  define GSNIMAGETOOLBOXSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GSNIMAGETOOLBOXSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GSNIMAGETOOLBOX_GLOBAL_H
